services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8090:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jobportal?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - db

  db:
    image: mysql:8.0.40
    environment:
      DATABASE_HOST: jobportal
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: jobportal
      MYSQL_DATABASE: jobportal
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: jobportal
